[package]
name = "i3owm"
version = "0.1.0"
authors = ["Patrick Hoffmann fightling@elektropost.org>"]
edition = "2018"
description = "Open Weather extension for i3status"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://github.com/fightling/i3owm"
homepage = "https://github.com/fightling/i3owm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.3", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "3.0.0-beta.2"
http = "0.2.4"
text_io = "0.1.8"
substring = "1.4.5"
serde_derive = "1.0.125"
regex = "1.4.6"
chrono = "0.4"
